name: Pipeline
on: [push]

jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build start target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: start
          tags: axiix/angular-starter-learning:start
      - name: Build target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: builder
          tags: axiix/angular-starter-learning:build
      - name: Build runtime target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: runtime
          tags: axiix/angular-starter-learning:runtime