name: Pipeline
on: [push]

jobs:
  build:
    name: Build our application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build start target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: start
          tags: axiix/angular-starter-learning:start
      - name: Build target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          target: builder
          tags: axiix/angular-starter-learning:build
      - name: Build runtime target
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          target: runtime
          tags: axiix/angular-starter-learning:${{ steps.tag_version.outputs.new_tag }}
      - name: Prepare helm chart
        run: |
          sed -i -e "s/BUILD_VERSION/${{ steps.tag_version.outputs.new_tag }}/g" charts/angular-starter-learning/Chart.yaml
          sed -i -e "s/HELM_VERSION/${{ steps.tag_version.outputs.new_version }}/g" charts/angular-starter-learning/Chart.yaml
          sed -i -e "s/BUILD_VERSION/${{ steps.tag_version.outputs.new_tag }}/g" charts/angular-starter-learning/values.yaml
      - name: Upload Helm chart
        uses: actions/upload-artifact@v2
        with:
          path: charts
          name: angular-starter-learning-chart